{"name": "Проверка, что возвращается ошибка, если создать двух одинаковых курьеров", "status": "passed", "start": 1731009476924, "stop": 1731009477054, "uuid": "1fefb3cc-69e0-4a61-8bdc-899a90a1f52d", "historyId": "866f420c19deaa63114aff9d131b07f4", "testCaseId": "866f420c19deaa63114aff9d131b07f4", "fullName": "tests.test_creating_courier.TestCreatingCourier#test_re_creation_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_creating_courier"}, {"name": "subSuite", "value": "TestCreatingCourier"}, {"name": "host", "value": "DESKTOP-ME9CEU9"}, {"name": "thread", "value": "25608-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_creating_courier"}]}